###

POST http://localhost:3000/comments
Content-Type: application/json

{
    "postId": "1",
    "owner": "Kfir",
    "content": "This is a comment"
}

###

GET http://localhost:3000/comments/post/1


###

GET http://localhost:3000/comments/67711700ddecf4fecb296703

###

DELETE http://localhost:3000/comments/674a2cb66c10bf2988371745

###

PUT http://localhost:3000/comments/67711700ddecf4fecb296703 
Content-Type: application/json

{
    "content": "changed comment"
}