###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "title": "Hello Kfir",
    "senderId": "12345",
    "content": "Hey, nice working with you"
}

###

GET http://localhost:3000/posts/all

###

GET http://localhost:3000/posts/6742373ddfdb9be9bf02aacf

###

GET http://localhost:3000/posts?sender=12345